### ISSUE TITLE
Splited

### ISSUE THREAD

**Issue by Archard2023** [player356377/Roblox-Starving-Artists-Image-Drawer-Cheat#2]
Can you fix the your image drawer because when i drew in roblox game it got separated 

Here is proof:
![RobloxScreenShot20230122_161124536](https://user-images.githubusercontent.com/123337980/213948050-b5b0213f-d8af-466b-b53f-d160179f532d.png)

**Comment by player356377** [comment]
@Archard2023, what is your screen resolution set to? The game has to be running in fullscreen mode and your Windows resolution has to be set to 1920x1080. Once I have time, I will possibly add support for all resolutions but for now the script only works in 1080p. I have run the script to verify if it still works and it worked perfectly for me.
